# frozen_string_literal: true

source "https://rubygems.org"

gem 'rails', '~> 7.0'
gem 'actionpack'
gem 'activejob'
gem 'activerecord'
gem 'sqlite3'
gem 'marcel'
gem 'cloudinary', path: '../../../'
gem 'rspec'
