# frozen_string_literal: true

source "https://rubygems.org"

gem 'rails', '~> 5.2'
gem 'actionpack', '~> 5.2'
gem 'activejob', '~> 5.2'
gem 'activerecord', '~> 5.2'
gem 'sqlite3'
gem 'marcel', '~> 0.3.1'
gem 'cloudinary', path: '../../../'
gem 'rspec'