source 'https://rubygems.org'

gem 'rails', '3.2.21'
gem 'sqlite3'
gem 'jquery-rails'

gem 'carrierwave'

gem 'cloudinary', :path => "../.."

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

gem 'test-unit'
# Optional - turbolinks support
#gem 'turbolinks'
#gem 'jquery-turbolinks'


