source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'sqlite3'
gem 'jquery-rails'

gem 'carrierwave'

gem 'cloudinary', '~> 1.0.71'

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

# Optional - turbolinks support
#gem 'turbolinks'
#gem 'jquery-turbolinks'


