source 'https://rubygems.org'

gem 'nio4r', '>= 2.7.1'
gem 'rails'
gem 'sqlite3'
gem 'jquery-rails'

gem 'sprockets-rails'

gem 'carrierwave'

gem 'cloudinary', :path => "../.."

group :assets do
  gem 'uglifier', '>= 1.0.3'
end

gem 'test-unit'
# Optional - turbolinks support
#gem 'turbolinks'
#gem 'jquery-turbolinks'
